forwarder.api-token=KM6D4RoIUe4dI1_5y1Ka69fnozo1CmwLjsLQy36AOd8
forwarder.decoder.host=localhost
forwarder.decoder.port=5100
forwarder.grpc.host=localhost
forwarder.grpc.port=9090
forwarder.grpc.plaintext=true
