forwarder.api-token=ykxrZLa8gaqafHlzb1KO1JJAWuYTEDlnmwPJRR-VNc8
forwarder.decoder.host=localhost
forwarder.decoder.port=5100
forwarder.grpc.host=localhost
forwarder.grpc.port=9090
forwarder.grpc.plaintext=true
