forwarder.api-token=fgpVbR__DIbkP6gW1VkZfLj1HEJpGI8zAIegqWOdlrY
forwarder.decoder.host=localhost
forwarder.decoder.port=5100
forwarder.grpc.host=localhost
forwarder.grpc.port=9090
forwarder.grpc.plaintext=true
