spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/rctiming_dev
    username: rctiming
    password: rctiming
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  jpa:
    hibernate:
      ddl-auto: validate
