spring:
  config:
    activate:
      on-profile: setup-test
  datasource:
    url: jdbc:postgresql://localhost:5432/rctiming_dev
    username: rctiming
    password: rctiming
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate

tts:
  endpoint: localhost:10200
